// src/pages/NoteView.tsx
import { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { getNote } from "@/lib/notes";
import { verifyPassword } from "@/lib/crypto";
import NoteViewer from "@/components/NoteViewer";
import { FileText, Loader2, Lock, Clock } from "lucide-react";
import { toast } from "sonner";

const NoteView = () => {
  const { id } = useParams<{ id: string }>();
  const [unlocked, setUnlocked] = useState(false);
  const [passwordInput, setPasswordInput] = useState("");
  const [verifying, setVerifying] = useState(false);

  const { data: note, isLoading, error } = useQuery({
    queryKey: ["note", id],
    queryFn: () => getNote(id!),
    enabled: !!id,
  });

  const isPasswordProtected = note?.password_hash && !unlocked;
  const isExpired = note?.expires_at && new Date(note.expires_at) <= new Date();

  const handleUnlock = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!note?.password_hash) return;
    setVerifying(true);
    const valid = await verifyPassword(passwordInput, note.password_hash);
    if (valid) {
      setUnlocked(true);
    } else {
      toast.error("Incorrect password");
    }
    setVerifying(false);
  };

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <FileText className="w-4 h-4 text-primary-foreground" />
            </div>
            <span className="font-bold text-lg text-foreground">NoteShare</span>
          </Link>
          <Link
            to="/"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            + New Note
          </Link>
        </div>
      </nav>

      <div className="px-6 py-12">
        {isLoading && (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
          </div>
        )}

        {error && (
          <div className="text-center py-20 animate-fade-in">
            <p className="text-xl font-semibold text-foreground">Note not found</p>
            <p className="mt-2 text-muted-foreground">
              This note may have been deleted, expired, or the link is invalid.
            </p>
            <Link
              to="/"
              className="inline-block mt-6 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:brightness-110 transition-all"
            >
              Create a New Note
            </Link>
          </div>
        )}

        {note && isExpired && (
          <div className="text-center py-20 animate-fade-in">
            <Clock className="w-10 h-10 mx-auto text-muted-foreground mb-4" />
            <p className="text-xl font-semibold text-foreground">Note Expired</p>
            <p className="mt-2 text-muted-foreground">
              This note expired on {new Date(note.expires_at!).toLocaleString()}.
            </p>
            <Link
              to="/"
              className="inline-block mt-6 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:brightness-110 transition-all"
            >
              Create a New Note
            </Link>
          </div>
        )}

        {note && !isExpired && isPasswordProtected && (
          <div className="max-w-md mx-auto text-center py-20 animate-fade-in">
            <div className="w-16 h-16 rounded-2xl bg-accent flex items-center justify-center mx-auto mb-6">
              <Lock className="w-7 h-7 text-accent-foreground" />
            </div>
            <p className="text-xl font-semibold text-foreground">This note is protected</p>
            <p className="mt-2 text-muted-foreground text-sm">
              Enter the password to view this note.
            </p>
            <form onSubmit={handleUnlock} className="mt-6 flex gap-2 max-w-xs mx-auto">
              <input
                type="password"
                placeholder="Password"
                value={passwordInput}
                onChange={(e) => setPasswordInput(e.target.value)}
                className="flex-1 px-4 py-3 rounded-xl border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring text-sm"
                autoFocus
              />
              <button
                type="submit"
                disabled={verifying || !passwordInput}
                className="px-5 py-3 rounded-xl bg-primary text-primary-foreground font-semibold text-sm hover:brightness-110 disabled:opacity-50"
              >
                {verifying ? <Loader2 className="w-4 h-4 animate-spin" /> : "Unlock"}
              </button>
            </form>
          </div>
        )}

        {note && !isExpired && !isPasswordProtected && <NoteViewer note={note} />}
      </div>
    </div>
  );
};

export default NoteView;

// resources/js/pages/NoteView.vue
<template>
  <div class="min-h-screen bg-background">
    <!-- Nav -->
    <Navbar>
      <template #actions>
        <div class="flex items-center gap-2">
          <router-link to="/" class="text-sm text-muted-foreground hover:text-foreground transition-colors">
            + New
          </router-link>
          <router-link
            v-if="canEdit"
            :to="`/notes/${note.id}/edit`"
            class="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors"
          >
            <Pencil class="w-4 h-4" />
            <span class="hidden sm:inline">Edit</span>
          </router-link>
        </div>
      </template>
    </Navbar>

    <div class="px-6 py-12">
      <!-- Loading -->
      <div v-if="loading" class="flex items-center justify-center py-20">
        <Loader2 class="w-6 h-6 animate-spin text-muted-foreground" />
      </div>

      <!-- Error -->
      <div v-else-if="error" class="text-center py-20 animate-fade-in">
        <FileText class="w-12 h-12 mx-auto text-muted-foreground mb-4" />
        <p class="text-xl font-semibold text-foreground">Note not found</p>
        <p class="mt-2 text-muted-foreground">This note may have been deleted, expired, or the link is invalid.</p>
        <router-link to="/" class="inline-block mt-6 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:brightness-110 transition-all">
          Go Home
        </router-link>
      </div>

      <!-- Note loaded -->
      <div v-else-if="note" class="w-full max-w-4xl mx-auto">

        <!-- Expired -->
        <div v-if="isExpired" class="text-center py-20 animate-fade-in">
          <Clock class="w-10 h-10 mx-auto text-muted-foreground mb-4" />
          <p class="text-xl font-semibold text-foreground">Note Expired</p>
          <p class="mt-2 text-muted-foreground">This note expired on {{ new Date(note.expires_at).toLocaleString() }}.</p>
          <router-link to="/" class="inline-block mt-6 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:brightness-110 transition-all">
            Go Home
          </router-link>
        </div>

        <!-- Password protected -->
        <div v-else-if="isPasswordProtected" class="max-w-md mx-auto text-center py-20 animate-fade-in">
          <div class="w-16 h-16 rounded-2xl bg-accent flex items-center justify-center mx-auto mb-6">
            <Lock class="w-7 h-7 text-accent-foreground" />
          </div>
          <p class="text-xl font-semibold text-foreground">This note is protected</p>
          <p class="mt-2 text-muted-foreground text-sm">Enter the password to view this note.</p>
          <form @submit.prevent="handleUnlock" class="mt-6 flex gap-2 max-w-xs mx-auto">
            <input
              type="password"
              placeholder="Password"
              v-model="passwordInput"
              class="flex-1 px-4 py-3 rounded-xl border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring text-sm"
              autofocus
            />
            <button
              type="submit"
              :disabled="verifying || !passwordInput"
              class="px-5 py-3 rounded-xl bg-primary text-primary-foreground font-semibold text-sm hover:brightness-110 disabled:opacity-50"
            >
              <Loader2 v-if="verifying" class="w-4 h-4 animate-spin" />
              <template v-else>Unlock</template>
            </button>
          </form>
        </div>

        <!-- Note content -->
        <div v-else class="animate-fade-in">
        <!-- Note card -->
        <div class="rounded-xl border bg-card overflow-hidden shadow-sm animate-fade-in">
          <!-- Action bar -->
          <div class="px-6 py-3 border-b bg-secondary/10 flex items-center justify-between gap-4 flex-wrap">
            <div class="flex items-center gap-2 text-[10px] text-muted-foreground uppercase tracking-widest font-bold">
              <span v-if="note.expires_at" class="flex items-center gap-1 text-primary">
                <Clock class="w-3 h-3" /> Expires {{ new Date(note.expires_at).toLocaleDateString() }}
              </span>
              <span class="font-mono">{{ note.format }}</span>
            </div>
            <div class="flex items-center gap-1">
              <button
                @click="copyLink"
                class="p-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all"
                title="Copy Link"
              >
                <Check v-if="copied" class="w-4 h-4 text-primary" />
                <Copy v-else class="w-4 h-4" />
              </button>
              <button
                @click="copyContent"
                class="p-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all"
                title="Copy Content"
              >
                <ClipboardCopy class="w-4 h-4" />
              </button>
              <router-link
                v-if="canEdit"
                :to="`/notes/${note.id}/edit`"
                class="p-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all"
                title="Edit"
              >
                <Pencil class="w-4 h-4" />
              </router-link>
            </div>
          </div>

          <!-- Title (Restored) -->
          <div v-if="note.title" class="px-8 pt-7 pb-2">
            <h1 class="text-2xl font-bold text-foreground leading-tight">{{ note.title }}</h1>
            <div class="border-b mt-4 opacity-30"></div>
          </div>

            <!-- Content: HTML rich text -->
            <div
              v-if="note.format === 'html' || note.format === 'text'"
              class="prose prose-neutral dark:prose-invert max-w-none px-8 py-6 text-foreground leading-7"
              v-html="cleanedContent"
            />

            <!-- Content: JSON -->
            <div v-else-if="note.format === 'json'" class="flex">
              <div class="select-none py-4 pr-2 pl-4 text-right border-r bg-secondary/30 min-w-[3.5rem]">
                <div v-for="i in jsonLineCount" :key="i" class="text-xs leading-6 text-muted-foreground font-mono">{{ i }}</div>
              </div>
              <pre class="flex-1 p-4 font-mono text-sm leading-6 text-foreground overflow-x-auto whitespace-pre-wrap">{{ cleanedContent }}</pre>
            </div>

            <!-- Fallback -->
            <div v-else class="px-8 py-6 text-sm leading-7 text-foreground whitespace-pre-wrap">{{ cleanedContent }}</div>
          </div>

        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { FileText, Loader2, Lock, Clock, Copy, Check, ClipboardCopy, Pencil } from 'lucide-vue-next';
import api from '../services/api';
import Navbar from '../components/Navbar.vue';

const route = useRoute();
const idOrSlug = route.params.idOrSlug;

const isLoggedIn = computed(() => !!localStorage.getItem('auth_token'));
const currentUserId = computed(() => {
  try {
    const user = JSON.parse(localStorage.getItem('auth_user') || 'null');
    return user?.id ?? null;
  } catch { return null; }
});
const note = ref(null);
const loading = ref(true);
const error = ref(null);
const unlocked = ref(false);
const passwordInput = ref('');
const verifying = ref(false);
const copied = ref(false);

const isPasswordProtected = computed(() => note.value?.password && !unlocked.value);
const isExpired = computed(() => note.value?.expires_at && new Date(note.value.expires_at) <= new Date());
const jsonLineCount = computed(() => (note.value?.content || '').split('\n').length);

const cleanedContent = computed(() => {
  if (!note.value || !note.value.content) return '';
  let content = note.value.content;
  
  if (note.value.title) {
    // Robust cleaning: Strip title from beginning of content
    const escapedTitle = note.value.title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const titleRegex = new RegExp(`^\\s*(<[^>]+>)*\\s*${escapedTitle}\\s*(<\\/[^>]+>)*`, 'i');
    
    if (titleRegex.test(content)) {
      content = content.replace(titleRegex, '').trim();
      // Also strip common leading formatting tags that might follow the title
      content = content.replace(/^(<br>|<p>&nbsp;<\/p>|<\/h[1-6]>|<p><\/p>)/i, '').trim();
    }
  }
  return content;
});

// Anyone can edit a guest note (no owner); only the owner can edit their own note
const canEdit = computed(() => {
  if (!note.value) return false;
  if (!note.value.user_id) return true;          // no owner — anyone can edit
  return currentUserId.value === note.value.user_id; // owner only
});

function formatSize(bytes) {
  if (!bytes) return '0 B';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1048576).toFixed(1)} MB`;
}

async function fetchNote() {
  loading.value = true;
  error.value = null;
  try {
    const response = await api.get(`/notes/${idOrSlug}`);
    note.value = response.data.data;
  } catch (err) {
    console.error(err);
    error.value = err;
  } finally {
    loading.value = false;
  }
}

async function handleUnlock() {
  verifying.value = true;
  try {
    const response = await api.get(`/notes/${idOrSlug}`, {
      params: { password: passwordInput.value }
    });
    note.value = response.data.data;
    unlocked.value = true;
  } catch (err) {
    console.error(err);
    alert('Incorrect password');
  } finally {
    verifying.value = false;
  }
}

async function copyLink() {
  await navigator.clipboard.writeText(window.location.href);
  copied.value = true;
  setTimeout(() => copied.value = false, 2000);
}

async function copyContent() {
  const text = note.value?.content || '';
  const plain = text.replace(/<[^>]*>/g, ''); // strip HTML tags
  await navigator.clipboard.writeText(plain);
}

onMounted(fetchNote);
</script>
