// lovable_backup/src/pages/Profile.tsx
import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { FileText, Loader2, User, Save, Camera } from "lucide-react";
import ThemeToggle from "@/components/ThemeToggle";

const Profile = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [displayName, setDisplayName] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");

  const { data: profile, isLoading } = useQuery({
    queryKey: ["profile", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", user!.id)
        .single();
      if (error) throw error;
      return data;
    },
    enabled: !!user,
  });

  useEffect(() => {
    if (profile) {
      setDisplayName(profile.display_name || "");
      setAvatarUrl(profile.avatar_url || "");
    }
  }, [profile]);

  const updateMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase
        .from("profiles")
        .update({
          display_name: displayName || null,
          avatar_url: avatarUrl || null,
        })
        .eq("id", user!.id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["profile"] });
      toast.success("Profile updated!");
    },
    onError: () => toast.error("Failed to update profile"),
  });

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <FileText className="w-4 h-4 text-primary-foreground" />
            </div>
            <span className="font-bold text-lg text-foreground">qor.so</span>
          </Link>
          <div className="flex items-center gap-2">
            <ThemeToggle />
            <Link
              to="/dashboard"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              MyDesk
            </Link>
          </div>
        </div>
      </nav>

      <div className="max-w-lg mx-auto px-6 py-16 animate-fade-in">
        <h1 className="text-3xl font-bold text-foreground text-center mb-8">My Profile</h1>

        {/* Avatar */}
        <div className="flex justify-center mb-8">
          <div className="relative">
            {avatarUrl ? (
              <img
                src={avatarUrl}
                alt="Avatar"
                className="w-24 h-24 rounded-2xl object-cover border-2 border-border"
              />
            ) : (
              <div className="w-24 h-24 rounded-2xl bg-accent flex items-center justify-center border-2 border-border">
                <User className="w-10 h-10 text-accent-foreground" />
              </div>
            )}
            <div className="absolute -bottom-1 -right-1 w-7 h-7 rounded-full bg-primary flex items-center justify-center">
              <Camera className="w-3.5 h-3.5 text-primary-foreground" />
            </div>
          </div>
        </div>

        <div className="space-y-5">
          {/* Email (read-only) */}
          <div>
            <label className="text-sm font-medium text-foreground mb-1.5 block">Email</label>
            <div className="px-4 py-3 rounded-xl border bg-secondary text-muted-foreground text-sm font-mono">
              {user?.email}
            </div>
          </div>

          {/* Display Name */}
          <div>
            <label className="text-sm font-medium text-foreground mb-1.5 block">Display Name</label>
            <input
              type="text"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="Your name"
              className="w-full px-4 py-3 rounded-xl border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring text-sm"
            />
          </div>

          {/* Avatar URL */}
          <div>
            <label className="text-sm font-medium text-foreground mb-1.5 block">Avatar URL</label>
            <input
              type="url"
              value={avatarUrl}
              onChange={(e) => setAvatarUrl(e.target.value)}
              placeholder="https://example.com/avatar.jpg"
              className="w-full px-4 py-3 rounded-xl border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring text-sm"
            />
          </div>

          <button
            onClick={() => updateMutation.mutate()}
            disabled={updateMutation.isPending}
            className="w-full py-3 rounded-xl bg-primary text-primary-foreground font-semibold text-sm hover:brightness-110 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
          >
            {updateMutation.isPending ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Save className="w-4 h-4" />
            )}
            Save Profile
          </button>
        </div>

        <p className="mt-8 text-center text-xs text-muted-foreground font-mono">
          Member since {new Date(profile?.created_at || "").toLocaleDateString()}
        </p>
      </div>
    </div>
  );
};

export default Profile;

// resources/js/pages/Profile.vue
<template>
  <div class="min-h-screen bg-background text-foreground">
    <!-- Navbar -->
    <Navbar>
      <template #actions>
        <router-link
          to="/dashboard"
          class="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors"
        >
          <LayoutDashboard class="w-4 h-4" />
          <span class="hidden sm:inline">MyDesk</span>
        </router-link>
      </template>
    </Navbar>

    <div class="max-w-lg mx-auto px-6 py-16 animate-fade-in">
      <h1 class="text-3xl font-bold text-foreground text-center mb-8">My Profile</h1>

      <div v-if="loading" class="flex justify-center py-10">
        <Loader2 class="w-8 h-8 animate-spin text-muted-foreground" />
      </div>

      <template v-else>
        <!-- Avatar -->
        <div class="flex justify-center mb-8">
          <div class="relative">
            <img
              v-if="user.avatar_url"
              :src="user.avatar_url"
              alt="Avatar"
              class="w-24 h-24 rounded-2xl object-cover border-2 border-border"
            />
            <div v-else class="w-24 h-24 rounded-2xl bg-accent flex items-center justify-center border-2 border-border">
              <UserIcon class="w-10 h-10 text-accent-foreground" />
            </div>
            <div class="absolute -bottom-1 -right-1 w-7 h-7 rounded-full bg-primary flex items-center justify-center">
              <Camera class="w-3.5 h-3.5 text-primary-foreground" />
            </div>
          </div>
        </div>

        <div class="space-y-6">
          <!-- Email (Editable) -->
          <div class="space-y-1.5">
            <div class="flex items-center justify-between">
              <label class="text-sm font-medium text-foreground">Login Email</label>
              <span class="text-[10px] font-bold text-primary uppercase tracking-tighter bg-primary/10 px-1.5 py-0.5 rounded">Critical</span>
            </div>
            <div class="relative group">
              <Mail class="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground transition-colors" />
              <input
                type="email"
                v-model="form.email"
                readonly
                class="w-full pl-11 pr-4 py-3.5 rounded-xl border bg-secondary/50 text-muted-foreground focus:outline-none transition-all text-sm font-mono cursor-not-allowed"
              />
            </div>
            <div class="mt-3 border border-primary/20 bg-primary/5 p-4 rounded-xl flex gap-3">
              <ShieldAlert class="h-4 w-4 text-primary shrink-0 mt-0.5" />
              <p class="text-[11px] text-muted-foreground leading-relaxed">
                This email is your <strong class="text-primary">secure login identity</strong>. It cannot be changed to ensure your account remains safe and your data accessible.
              </p>
            </div>
          </div>

          <!-- Display Name -->
          <div>
            <label class="text-sm font-medium text-foreground mb-1.5 block">Display Name</label>
            <input
              type="text"
              v-model="form.display_name"
              placeholder="Your name"
              class="w-full px-4 py-3 rounded-xl border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring text-sm"
            />
          </div>

          <!-- Avatar URL -->
          <div>
            <label class="text-sm font-medium text-foreground mb-1.5 block">Avatar URL</label>
            <input
              type="url"
              v-model="form.avatar_url"
              placeholder="https://example.com/avatar.jpg"
              class="w-full px-4 py-3 rounded-xl border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring text-sm"
            />
          </div>

          <button
            @click="updateProfile"
            :disabled="updating"
            class="w-full py-3 rounded-xl bg-primary text-primary-foreground font-semibold text-sm hover:brightness-110 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <Loader2 v-if="updating" class="w-4 h-4 animate-spin" />
            <Save v-else class="w-4 h-4" />
            Save Profile
          </button>
        </div>

        <p class="mt-8 text-center text-xs text-muted-foreground font-mono">
          Member since {{ new Date(user.created_at).toLocaleDateString() }}
        </p>
      </template>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { FileText, Loader2, User as UserIcon, Save, Camera, LayoutDashboard, ShieldAlert, Mail } from 'lucide-vue-next';
import Navbar from '../components/Navbar.vue';
import api from '../services/api';

const user = ref(null);
const loading = ref(true);
const updating = ref(false);

const form = ref({
  display_name: '',
  avatar_url: ''
});

async function fetchUser() {
  try {
    const response = await api.get('/user');
    user.value = response.data.data;
    form.value.email = user.value.email || '';
    form.value.display_name = user.value.display_name || user.value.name || '';
    form.value.avatar_url = user.value.avatar_url || '';
  } catch (err) {
    console.error(err);
  } finally {
    loading.value = false;
  }
}

import { useNotifications } from '../stores/useNotifications';
const toast = useNotifications();

async function updateProfile() {
  updating.value = true;
  try {
    const { email, ...payload } = form.value;
    const response = await api.put('/user/profile', payload);
    user.value = response.data.data;
    toast.success('Profile updated!');
  } catch (err) {
    console.error(err);
    toast.error('Failed to update profile');
  } finally {
    updating.value = false;
  }
}

onMounted(fetchUser);
</script>
